In [18]:
import numpy as np
from scipy import sparse
from scipy.sparse import linalg, csgraph

In [3]:
row = [1, 3, 0, 2, 4]
col = [1, 4, 2, 3, 3]
data = [2, 5, 9, 1, 6]
coo = sparse.coo_matrix((data, (row, col)), shape=(6, 7))
print(coo)
coo.toarray()

  (1, 1)	2
  (3, 4)	5
  (0, 2)	9
  (2, 3)	1
  (4, 3)	6


array([[0, 0, 9, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [4]:
lil = sparse.lil_matrix((6, 5), dtype=np.int)
lil[(0, -1)] = -1
lil[3, (0, 4)] = [-2] * 2
lil.setdiag(8, k=0)
lil[:, 2] = np.arange(lil.shape[0]).reshape(-1, 1) + 1
lil.toarray()

array([[ 8,  0,  1,  0, -1],
       [ 0,  8,  2,  0,  0],
       [ 0,  0,  3,  0,  0],
       [-2,  0,  4,  8, -2],
       [ 0,  0,  5,  0,  8],
       [ 0,  0,  6,  0,  0]])

In [5]:
indptr = np.array([0, 2, 3, 3, 3, 6, 6, 7])
indices = np.array([0, 2, 2, 2, 3, 4, 3])
data = np.array([8, 2, 5, 7, 1, 2, 9])

csr = sparse.csr_matrix((data, indices, indptr))

csr.toarray()

array([[8, 0, 2, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 7, 1, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 9, 0]])

In [6]:
csc = sparse.csc_matrix(csr)
print(csc.indptr)
print(csc.indices)
print(csc.data)
print(csc.toarray())

[0 1 1 4 6 7]
[0 0 1 4 4 6 4]
[8 2 5 7 1 9 2]
[[8 0 2 0 0]
 [0 0 5 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 7 1 2]
 [0 0 0 0 0]
 [0 0 0 9 0]]


In [7]:
data = np.arange(15).reshape(3, -1) + 1
offsets = np.array([0, -3, 2])
print(data)
dia = sparse.dia_matrix((data, offsets), shape=(7, 5))
print(dia.toarray())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  0 13  0  0]
 [ 0  2  0 14  0]
 [ 0  0  3  0 15]
 [ 6  0  0  4  0]
 [ 0  7  0  0  5]
 [ 0  0  8  0  0]
 [ 0  0  0  9  0]]


In [8]:
sparse.spmatrix.mean(dia)

2.4857142857142858

In [10]:
sparse.spmatrix.getcol(coo, 1).toarray()

array([[0],
       [2],
       [0],
       [0],
       [0],
       [0]], dtype=int32)

In [11]:
sparse.spmatrix.getmaxprint(coo)

50

In [12]:
sparse.isspmatrix_coo(dia), sparse.isspmatrix_coo(coo)

(False, True)

In [ ]:
csgraph.bellman_ford()